import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { homePath, ticketsPath } from "@/path";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "The Road Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header>
          <nav className="supports-backdrop-blur:bg-background/60 fixed left-0 right-0 top-0 z-20 border-b bg-background/95 backdrop-blur w-full flex py-2.5 px-5 justify-between">
            <div>
              <Link href={homePath()} className="text-lg font-bold">Home</Link>
              <Link href={ticketsPath()} className="text-sm underline">Tickets</Link>
            </div>
            <div>
            </div>
          </nav>
        </header>
        <main className="min-h-screen flex-1 overflow-y-auto overflow-x-hidden over py-24 px-8 flex flex-col">
          {children}
        </main>
      </body>
    </html>
  );
}
